repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      name: Run Formatter
      files: ^src/    

-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    - id: flake8
      name: Run Code Quality
      files: ^src/     

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      name: Run Lint
      files: ^src/
      
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2  # ou a versão mais recente
    hooks:
    - id: isort
      name: Run Isort
      files: ^src/        

-   repo: local
    hooks:
    - id: pytest
      name: Run Unit Tests
      entry: pytest tests/
      language: system  # ou "python" com dependencies, se preferir
      types: [python]
      pass_filenames: false  