name: Release Please

on:
  push:
    branches:
      - main  # ou sua branch principal (ex: master)

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple # python, node, java
