name: Release Please

on:
  push:
    branches:
      - main  # ou sua branch principal (ex: master)

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action
        with:
          release-type: python  # node, java, simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
